version: '3.8'

services:
  mysql-master:
    image: registry.cn-shanghai.aliyuncs.com/wukongim/mysql:8.0.33
    container_name: mysql-master
    environment:
      # 请设置一个安全密码
      MYSQL_ROOT_PASSWORD: af45d4daS*
      # 复制用户
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: af45d4daS*
    ports:
      - "3316:3306"
    volumes:
      # 挂载自定义配置文件
      - ./conf/master.cnf:/etc/mysql/conf.d/master.cnf
      - ./conf/certs/:/etc/mysql/certs/:ro 
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-paf45d4daS*"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-slave1:
    image: registry.cn-shanghai.aliyuncs.com/wukongim/mysql:8.0.33
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: af45d4daS*
    ports:
      - "3317:3306" # 映射到宿主机的 3307 端口
    volumes:
      - ./conf/slave1.cnf:/etc/mysql/conf.d/slave1.cnf
      - ./conf/certs/:/etc/mysql/certs/:ro 
    command: --default-authentication-plugin=mysql_native_password
    depends_on:
      - mysql-master

  mysql-slave2:
    image: registry.cn-shanghai.aliyuncs.com/wukongim/mysql:8.0.33
    container_name: mysql-slave2
    environment:
      MYSQL_ROOT_PASSWORD: af45d4daS*
    ports:
      - "3318:3306" # 映射到宿主机的 3308 端口
    volumes:
      - ./conf/slave2.cnf:/etc/mysql/conf.d/slave2.cnf
      - ./conf/certs/:/etc/mysql/certs/:ro 
    command: --default-authentication-plugin=mysql_native_password
    depends_on:
      - mysql-master

  proxysql:
    image: proxysql/proxysql:2.5.5 # 推荐使用最新的稳定版本
    container_name: proxysql
    ports:
      - "6033:6033" # 应用程序连接端口
      - "6032:6032" # ProxySQL 管理端口 (Admin)
    volumes:
      - ./proxysql/conf:/etc/proxysql:ro
      - ./proxysql/data:/var/lib/proxysql
    depends_on:
      - mysql-master
      - mysql-slave1
    environment:
      # ProxySQL 管理员密码 (用于连接 6032 端口进行配置)
      PROXYSQL_ADMIN_PASSWORD: af45d4daS*